Addition of GRAVITY curve
nasavbailey/DI-flux-ratio-plot pull request #11
Opened 2024-07-25 12:59 UTC by npourre

Dear Vanessa Bailey,

my paper with the exoplanet detection curve of GRAVITY is now published! As we already discussed by email the pertinence of adding it to your DI-flux-ratio-plot, it took the liberty to fork your repo and make the changes.

It includes:
- changes in the default.yml and doc.yml config files to add the GRAVITY option
- description and reference in description.md
- changes in plot_flux_ratio.py: plot GRAVITY curve + lower xlim extension to 40 mas when plotted.

Thanks a lot, I used your code extensively during my thesis (always citing it ;) )
I remain at your disposal for any information or modification.

Cheers,

Nicolas

2024-09-14 00:24 UTC, nasavbailey requested changes
My apologies that I took so long to do this review! Thank you for submitting GRAVITY! I have only one required change to the default YAML and one suggested change to plot_flux_ratio.py.

2024-09-14 00:24 UTC, nasavbailey commented on example_files/default.yml
Can you please revert to the original default settings for generic, SPHERE, and GPI (True, False, False, respectively)?  GRAVITY can either be True or False by default, whichever is your preference.

2024-09-14 00:24 UTC, nasavbailey commented on plot_flux_ratio.py
I suggest that GRAVITY is not hidden when 'generic ground-based' is True, because GRAVITY is a different flavor than the rest of the instruments, which are all direct coronagraphic imaging. In other words, no need to make GRAVITY conditional on Generic=False.

2024-09-16 13:55 UTC, npourre commented on example_files/default.yml
Yes! I put back generic = True, and GRAVITY = True.

2024-09-16 13:57 UTC, npourre commented on plot_flux_ratio.py
I agree. It is meaningful to have both "generic ground-based" and GRAVITY. And it looks nice! 
![image](https://github.com/user-attachments/assets/51711027-2a36-4957-8310-5f849b6b28de)

2024-09-16 13:59 UTC, npourre commented
No worries for the delay! I have committed the changes, it should be ok now.
Do not hesitate if you identify other problems.

2024-09-17 18:26 UTC, nasavbailey reviewed
looks good

2024-09-17 18:29 UTC, nasavbailey approved these changes

2024-09-17 18:29 UTC, merged